spring:
  datasource:
    url: jdbc:mysql://smileyan.cn:3306/songci?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: yourpasswd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
page_size: 8